// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace CompiledModels
{
    public partial class ApplicationDbContextModel
    {
        partial void Initialize()
        {
            var identityRole = IdentityRoleEntityType.Create(this);
            var identityRoleClaim = IdentityRoleClaimEntityType.Create(this);
            var identityUser = IdentityUserEntityType.Create(this);
            var identityUserClaim = IdentityUserClaimEntityType.Create(this);
            var identityUserLogin = IdentityUserLoginEntityType.Create(this);
            var identityUserRole = IdentityUserRoleEntityType.Create(this);
            var identityUserToken = IdentityUserTokenEntityType.Create(this);
            var blogCategory = BlogCategoryEntityType.Create(this);
            var blogPost = BlogPostEntityType.Create(this);
            var callToActionMessage = CallToActionMessageEntityType.Create(this);
            var callToActionSetting = CallToActionSettingEntityType.Create(this);
            var companyCertificate = CompanyCertificateEntityType.Create(this);
            var companyCertificateSetting = CompanyCertificateSettingEntityType.Create(this);
            var companyInfo = CompanyInfoEntityType.Create(this);
            var companyQuality = CompanyQualityEntityType.Create(this);
            var companyQualitySetting = CompanyQualitySettingEntityType.Create(this);
            var companyStory = CompanyStoryEntityType.Create(this);
            var companyValue = CompanyValueEntityType.Create(this);
            var heroSlider = HeroSliderEntityType.Create(this);
            var heroSliderImage = HeroSliderImageEntityType.Create(this);
            var imageModel = ImageModelEntityType.Create(this);
            var legalDocument = LegalDocumentEntityType.Create(this);
            var member = MemberEntityType.Create(this);
            var project = ProjectEntityType.Create(this);
            var projectTag = ProjectTagEntityType.Create(this);
            var service = ServiceEntityType.Create(this);
            var serviceType = ServiceTypeEntityType.Create(this);
            var tag = TagEntityType.Create(this);
            var testimony = TestimonyEntityType.Create(this);
            var applicationUser = ApplicationUserEntityType.Create(this, identityUser);

            IdentityRoleClaimEntityType.CreateForeignKey1(identityRoleClaim, identityRole);
            IdentityUserClaimEntityType.CreateForeignKey1(identityUserClaim, identityUser);
            IdentityUserLoginEntityType.CreateForeignKey1(identityUserLogin, identityUser);
            IdentityUserRoleEntityType.CreateForeignKey1(identityUserRole, identityRole);
            IdentityUserRoleEntityType.CreateForeignKey2(identityUserRole, identityUser);
            IdentityUserTokenEntityType.CreateForeignKey1(identityUserToken, identityUser);
            HeroSliderImageEntityType.CreateForeignKey1(heroSliderImage, heroSlider);
            ImageModelEntityType.CreateForeignKey1(imageModel, project);
            ProjectTagEntityType.CreateForeignKey1(projectTag, project);
            ProjectTagEntityType.CreateForeignKey2(projectTag, tag);
            TestimonyEntityType.CreateForeignKey1(testimony, project);

            IdentityRoleEntityType.CreateAnnotations(identityRole);
            IdentityRoleClaimEntityType.CreateAnnotations(identityRoleClaim);
            IdentityUserEntityType.CreateAnnotations(identityUser);
            IdentityUserClaimEntityType.CreateAnnotations(identityUserClaim);
            IdentityUserLoginEntityType.CreateAnnotations(identityUserLogin);
            IdentityUserRoleEntityType.CreateAnnotations(identityUserRole);
            IdentityUserTokenEntityType.CreateAnnotations(identityUserToken);
            BlogCategoryEntityType.CreateAnnotations(blogCategory);
            BlogPostEntityType.CreateAnnotations(blogPost);
            CallToActionMessageEntityType.CreateAnnotations(callToActionMessage);
            CallToActionSettingEntityType.CreateAnnotations(callToActionSetting);
            CompanyCertificateEntityType.CreateAnnotations(companyCertificate);
            CompanyCertificateSettingEntityType.CreateAnnotations(companyCertificateSetting);
            CompanyInfoEntityType.CreateAnnotations(companyInfo);
            CompanyQualityEntityType.CreateAnnotations(companyQuality);
            CompanyQualitySettingEntityType.CreateAnnotations(companyQualitySetting);
            CompanyStoryEntityType.CreateAnnotations(companyStory);
            CompanyValueEntityType.CreateAnnotations(companyValue);
            HeroSliderEntityType.CreateAnnotations(heroSlider);
            HeroSliderImageEntityType.CreateAnnotations(heroSliderImage);
            ImageModelEntityType.CreateAnnotations(imageModel);
            LegalDocumentEntityType.CreateAnnotations(legalDocument);
            MemberEntityType.CreateAnnotations(member);
            ProjectEntityType.CreateAnnotations(project);
            ProjectTagEntityType.CreateAnnotations(projectTag);
            ServiceEntityType.CreateAnnotations(service);
            ServiceTypeEntityType.CreateAnnotations(serviceType);
            TagEntityType.CreateAnnotations(tag);
            TestimonyEntityType.CreateAnnotations(testimony);
            ApplicationUserEntityType.CreateAnnotations(applicationUser);

            AddAnnotation("ProductVersion", "7.0.16");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
